### ISSUE TITLE
[bug-report] Crash when using <tab> as separator, but input headers are separated by space

### ISSUE THREAD

**Issue by TLINDEN** [TLINDEN/tablizer#27]
**Description**
If an input's headers are separated by space but the user specified `-s '\t'` then tablizer crashes.

**Steps To Reproduce**

```default
% cat -T table.txt 
id name size
1 joe 8
4 ^Imax ^I 19
9 ^Icic ^I 6

cat table.txt | t -s '\t'  -X
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/tlinden/tablizer/lib.printExtendedData({_, _}, {0x0, 0x0, 0x0, {0x0, 0x0}, {0x0, 0x0, 0x0}, ...}, ...)
        /home/scip/dev/tablizer/lib/printer.go:174 +0x325
github.com/tlinden/tablizer/lib.printData({_, _}, {0x0, 0x0, 0x0, {0x0, 0x0}, {0x0, 0x0, 0x0}, ...}, ...)
        /home/scip/dev/tablizer/lib/printer.go:47 +0x1d5
github.com/tlinden/tablizer/lib.ProcessFiles(0xc0001be1c0, {0xc0001d3d10?, 0x0?, 0x0?})
        /home/scip/dev/tablizer/lib/io.go:53 +0xec
github.com/tlinden/tablizer/cmd.Execute.func1(0xc0001d0a00?, {0xc0001d3d10, 0x0, 0x3})
        /home/scip/dev/tablizer/cmd/root.go:121 +0x2f7
github.com/spf13/cobra.(*Command).execute(0xc0001e8308, {0xc0000240d0, 0x3, 0x3})
        /home/scip/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x882
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001e8308)
        /home/scip/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /home/scip/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/tlinden/tablizer/cmd.Execute()
        /home/scip/dev/tablizer/cmd/root.go:198 +0xb65
main.main()
        /home/scip/dev/tablizer/main.go:25 +0xf
```

**Expected behavior**

Print some data or an error message.

**Version information**
latest.

**Comment by TLINDEN** [comment]
The problem is, that in this case the number of headers does not match the number of elements per row.
