### ISSUE TITLE
[bug-report] Crash when using non-file argument to -f

### ISSUE THREAD

**Issue by TLINDEN** [TLINDEN/tablizer#29]
A call like this:
```default
tablizer -f "DESCRIPTION=(foo|bar)"
```

leads to:

```default
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x89caee]

goroutine 1 [running]:
github.com/tlinden/tablizer/cfg.(*Config).ParseConfigfile(0xc000102c40)
        /home/scip/dev/tablizer/cfg/config.go:331 +0x6e
github.com/tlinden/tablizer/cmd.Execute.func1(0xc00020ea00?, {0xc000164540, 0x0, 0xc})
        /home/scip/dev/tablizer/cmd/root.go:109 +0x7d
github.com/spf13/cobra.(*Command).execute(0xc000222308, {0xc0001201b0, 0xc, 0xc})
        /home/scip/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0xc000222308)
        /home/scip/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/scip/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/tlinden/tablizer/cmd.Execute()
        /home/scip/dev/tablizer/cmd/root.go:201 +0xb65
main.main()
        /home/scip/dev/tablizer/main.go:25 +0xf
```

The user meant to supply a filter arg, but that would be `-F` not `-f` which is being treated as a config file, but should lead to a meaningful error message, not a crash.

**Comment by TLINDEN** [comment]
Happens **ONLY** when filename given to `-f` is longer than 255 chars!
